/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package basiclibrary;

import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.List;

import static org.junit.jupiter.api.Assertions.*;

class LibraryTest {
    @Test void someLibraryMethodReturnsTrue() {
        Library classUnderTest = new Library();
        assertTrue(classUnderTest.someLibraryMethod(), "someLibraryMethod should return 'true'");
    }

    @Test void rollSomeDice(){
        Library classUnderTest = new Library();
        assertEquals(classUnderTest.roll(5).length, 5, "success");
    }

    @Test void testForDuplicates(){
        Library classUnderTest = new Library();
        int[] testArr1 = {1,2,3,4,5,6};
        int[] testArr2 = {1,2,2,4,5,6};
        int[] testArr3 = {1,2,3,4,5,5};
        int[] testArr4 = {1,6,3,4,9,5};

        assertFalse(classUnderTest.conatinsDuplicates(testArr1));
        assertTrue(classUnderTest.conatinsDuplicates(testArr2));
        assertTrue(classUnderTest.conatinsDuplicates(testArr3));
        assertFalse(classUnderTest.conatinsDuplicates(testArr4));
    }

    @Test void testAverage(){
        Library classUnderTest = new Library();
        int[] testCase1 = {66, 64, 58, 65, 71, 57, 60};
        float testAvg1 = 63f;

        int[] testCase2 = {1,2,3,4,5,6};
        float testAvg2 = 3.5f;


        assertEquals(classUnderTest.average(testCase1), testAvg1);
        assertEquals(classUnderTest.average(testCase2), testAvg2);
    }

    @Test void testMatrixLowestAverage(){
        Library classUnderTest = new Library();
        int[][] testCase = {
                {66, 64, 58, 65, 71, 57, 60}, //441
                {57, 65, 65, 70, 72, 65, 51}, //445
                {55, 54, 60, 53, 59, 57, 61}, //399
                {65, 56, 55, 52, 55, 62, 57}  //402
        };

        int [] testAns = {55, 54, 60, 53, 59, 57, 61};
        assertArrayEquals(classUnderTest.returnArrLowestAverage(testCase), testAns);
    }

    @Test void testWeatherData(){
        Library classUnderTest = new Library();

        int[][] testCase = {
                {66, 64, 58, 65, 71, 57, 60}, //441
                {57, 65, 65, 70, 72, 65, 51}, //445
                {55, 54, 60, 53, 59, 57, 61}, //399
                {65, 56, 55, 52, 55, 62, 57}  //402
        };

        String expected = "High: 72\n" +
                "Low: 51\n" +
                "Never saw temperature: 63\n" +
                "Never saw temperature: 67\n" +
                "Never saw temperature: 68\n" +
                "Never saw temperature: 69";

        assertEquals(classUnderTest.analyzeWeatherData(testCase), expected);
    }

    @Test void testTally() {
        Library classUnderTest = new Library();
        List<String> votes = new ArrayList<>();
        votes.add("Bush");
        votes.add("Bush");
        votes.add("Bush");
        votes.add("Shrub");
        votes.add("Hedge");
        votes.add("Shrub");
        votes.add("Bush");
        votes.add("Hedge");
        votes.add("Bush");

        String expected = "Bush received the most votes!";
        assertEquals(expected, classUnderTest.tally((votes)));
    }
}
