/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package basiclibrary;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }

    public int[] roll(int numRolls){
        int[] retRolls = new int[numRolls];

        for(int i = 0; i < numRolls; i++ ){
            int roll = (int)Math.ceil(Math.random() * 6);
            System.out.println(roll);
            retRolls[i] = roll;
        }
        return retRolls;
    }

    public boolean conatinsDuplicates(int[] arr){
        for(int i = 0; i <= arr.length; i++){
            for(int j = i+1; j < arr.length; j++){
                if(arr[j] == arr[i]){
                    return true;
                }
            }
        }
        return false;
    }

    public float average(int[] arr){
        float total = 0f;
        for (int i = 0; i < arr.length; i++){
            total += arr[i];
        }
        return total/arr.length;
    }

    public int[] returnArrLowestAverage(int[][] arr){
        int index = 0;
        float lowAvg = average(arr[index]);
        for (int i = 1; i < arr.length; i++){
            float testAvg = average(arr[i]);
            if(testAvg < lowAvg){
                lowAvg = testAvg;
                index = i;
            }
        }
        return arr[index];
    }
}
