/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package inheritance;

public class Review {
    public String name;
    public String body;
    public int rating;
    public Restaurant subject;
    private final String star = "⭐️";

    public Review(String name, String body, int rating, Restaurant subject){
        this.name = name;
        this.body = body;
        this.rating = rating;
        this.subject = subject;
        subject.addReview(this);
    }

    public static String ratingString(int rating, String character){
        String retStr = "";
        for(int i = 0; i < rating; i++){
            retStr += character;
        }
        return retStr;
    }

    @Override
    public String toString(){
        String reviewString = "Review of " + subject.name + " " + ratingString(rating, star) + " " + body + " -" + name;
        return reviewString;
    }
}
