/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linter;

import java.io.IOException;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.Scanner;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    //46 errors, thanks austin

    public static void main(String[] args) throws IOException {
        Path gatePath = Paths.get("app/src/main/resources/gates.js");

        linter(gatePath);
    }

    public static int linter(Path path) throws IOException {
        Scanner scanner = new Scanner(path);
        int lineNum = 0;
        int errCount = 0;

        while(scanner.hasNext()){
            String line = "";
            while(line.equals("")){
                lineNum++;
                line = scanner.nextLine();
            }
            if(!line.endsWith(";") && !line.endsWith("{") && !line.endsWith("}")){
                if(line.contains("if") | line.contains("else")){
                    continue;
                }
                String missingSemi = "Line " + lineNum + ": Missing semicolon!";
                errCount++;
//                System.out.println(missingSemi);
            }
        }
//        System.out.println("\nNum errors in file: " + errCount + "\n");
        return errCount;
    }
}
