/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linter;

import org.junit.jupiter.api.Test;

import java.io.IOException;
import java.nio.file.Path;
import java.nio.file.Paths;

import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() throws IOException {
        App classUnderTest = new App();

        Path gatePath = Paths.get("src/test/resources/gates.js");
        Path path0 = Paths.get("src/test/resources/noErr.js");
        Path path1 = Paths.get("src/test/resources/oneErr.js");
        Path path2 = Paths.get("src/test/resources/fiveErr.js");

        assertEquals(46, classUnderTest.linter(gatePath), "TEST PASSED!");
        assertEquals(0, classUnderTest.linter(path0), "TEST PASSED!");
        assertEquals(1, classUnderTest.linter(path1), "TEST PASSED!");
        assertEquals(5, classUnderTest.linter(path2), "TEST PASSED!");

    }
}
